version: '3.8'

services:
  db:
    image: mysql:8.0.30-debian
    container_name: springboot-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api-order
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/api-order
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: on-failure

volumes:
  db_data:
